name: Publish to Microsoft Store (not functional)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-windows.yml  # Call reusable build

  check-tag-origin:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      is_main: ${{ steps.check.outputs.is_main }}
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag is on main
        id: check
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          if git branch --contains $TAG_COMMIT | grep -q "main"; then
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: windows-latest
    needs: [build, check-tag-origin]
    if: needs.check-tag-origin.outputs.is_main == 'true'

    steps:
      - name: Checkout at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download MSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: msix-package-for-store
          path: msix_upload

      - name: Find MSIX file path
        id: msix
        run: |
          $file = Get-ChildItem -Path msix_upload -Filter *.msix | Select-Object -First 1
          echo "msix_path=$($file.FullName)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Configure Store Submission
        uses: microsoft/store-submission@v1
        with:
          command: configure
          type: win32
          seller-id: ${{ secrets.SELLER_ID }}
          product-id: ${{ secrets.PRODUCT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Update Submission with local MSIX
        uses: microsoft/store-submission@v1
        with:
          command: update
          product-update: |
            {
              "packages": [
                {
                  "filePath": "${{ env.msix_path }}",
                  "languages": ["en"],
                  "architectures": ["x64"],
                  "isSilentInstall": true
                }
              ]
            }

      - name: Publish to Microsoft Store
        uses: microsoft/store-submission@v1
        with:
          command: publish
