name: Test build

on:
  workflow_dispatch: # Manual triggering
  push: # Trigger on push events
    branches:
      - main # Adjust this to your main branch if different

jobs:
  windows-build:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  linux-build:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  windows-xp-build:
    uses: ./.github/workflows/build-windows-legacy.yml
    secrets: inherit
